# Generated by Django 4.2 on 2023-04-18 03:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DublinBusRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_name', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('stop_lon', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('trip_id', models.CharField(blank=True, max_length=45, null=True)),
                ('arrival_time', models.CharField(blank=True, max_length=45, null=True)),
                ('departure_time', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_sequence', models.IntegerField(blank=True, null=True)),
                ('stop_headsign', models.CharField(blank=True, max_length=45, null=True)),
                ('shape_dist_traveled', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('route_id', models.CharField(blank=True, max_length=45, null=True)),
                ('customer_route', models.CharField(blank=True, max_length=45, null=True)),
                ('project_subnet', models.CharField(blank=True, max_length=45, null=True)),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'dublin_bus_routes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DublinStops',
            fields=[
                ('stop_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('stop_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('stop_lon', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'dublin_stops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_name', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('stop_lon', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('trip_id', models.CharField(blank=True, max_length=45, null=True)),
                ('arrival_time', models.CharField(blank=True, max_length=45, null=True)),
                ('departure_time', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_sequence', models.IntegerField(blank=True, null=True)),
                ('stop_headsign', models.CharField(blank=True, max_length=45, null=True)),
                ('shape_dist_traveled', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('route_id', models.CharField(blank=True, max_length=45, null=True)),
                ('customer_route', models.CharField(blank=True, max_length=45, null=True)),
                ('project_subnet', models.CharField(blank=True, max_length=45, null=True)),
                ('geo_point', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'routes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shapes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.CharField(blank=True, max_length=30, null=True)),
                ('shape_pt_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('shape_pt_lon', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('shape_pt_sequence', models.IntegerField(blank=True, null=True)),
                ('shape_dist_traveled', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('routes_point', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'shapes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShpShp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('file', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'shp_shp',
                'managed': False,
            },
        ),
    ]
