# Generated by Django 4.2 on 2023-04-18 06:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dublinbusroutes_dublinstops_routes_shapes_shpshp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('place_id', models.CharField(blank=True, max_length=45, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
